# Generated by Django 4.2.2 on 2023-08-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogenie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='views',
        ),
    ]
